remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Cloud Express"
description: Your Perfect Starting Point To The Cloud with Yaya Legacy.
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine